In [1]:
import pandas as pd
import numpy as np

In [2]:
people ={
    'first' : ['Corey','Anand','Aditya','Ashish','Prateek',np.nan,None,'NA'],
    'last' : ['Schafar','Jaiswal','Jaiswal','Jaiswal','Rastogi',np.nan,np.nan,None],
    'email' : ['corey@gmail.com','anand@gmail.com','aditya@gmail.com',None,'prateek@gmail.com',None,np.nan ,'missing@gmail.com'],
     'age' : ['33','18','18','19','20',None,None,None]
}

In [3]:
df =pd.DataFrame(people)
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
3   Ashish  Jaiswal                NaN   19
4  Prateek  Rastogi  prateek@gmail.com   20
5      NaN      NaN                NaN  NaN
6      NaN      NaN                NaN  NaN
7      NaN      NaN  missing@gmail.com  NaN

In [4]:
df

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
3   Ashish  Jaiswal                NaN   19
4  Prateek  Rastogi  prateek@gmail.com   20
5      NaN      NaN                NaN  NaN
6      NaN      NaN                NaN  NaN
7      NaN      NaN  missing@gmail.com  NaN

In [5]:
df.dropna()  #drops all rows having any  missing column

     first     last              email age
0    Corey  Schafar    corey@gmail.com  33
1    Anand  Jaiswal    anand@gmail.com  18
2   Aditya  Jaiswal   aditya@gmail.com  18
4  Prateek  Rastogi  prateek@gmail.com  20

In [6]:
df.dropna(axis='index',how ='any')  # this is same as above by default function of dropna function

     first     last              email age
0    Corey  Schafar    corey@gmail.com  33
1    Anand  Jaiswal    anand@gmail.com  18
2   Aditya  Jaiswal   aditya@gmail.com  18
4  Prateek  Rastogi  prateek@gmail.com  20

In [7]:
df.dropna(axis='index',how='all')   # this will remove only those rows having all values missing

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
3   Ashish  Jaiswal                NaN   19
4  Prateek  Rastogi  prateek@gmail.com   20
7      NaN      NaN  missing@gmail.com  NaN

In [8]:
df.dropna(axis='columns',how ='all')

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
3   Ashish  Jaiswal                NaN   19
4  Prateek  Rastogi  prateek@gmail.com   20
5      NaN      NaN                NaN  NaN
6      NaN      NaN                NaN  NaN
7      NaN      NaN  missing@gmail.com  NaN

In [9]:
df.dropna(axis='columns',how ='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

In [10]:
df.dropna(axis='index',how ='any',subset =['email'])  # this gives rows which have  email in them

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
4  Prateek  Rastogi  prateek@gmail.com   20
7      NaN      NaN  missing@gmail.com  NaN

In [11]:
df.dropna(axis='index',how ='any',subset =['email','last'])  # remove those which do not have either the last or the email

     first     last              email age
0    Corey  Schafar    corey@gmail.com  33
1    Anand  Jaiswal    anand@gmail.com  18
2   Aditya  Jaiswal   aditya@gmail.com  18
4  Prateek  Rastogi  prateek@gmail.com  20

In [12]:
df.dropna(axis='index',how ='all',subset =['email','last'])  # remove those not having both last and email

     first     last              email  age
0    Corey  Schafar    corey@gmail.com   33
1    Anand  Jaiswal    anand@gmail.com   18
2   Aditya  Jaiswal   aditya@gmail.com   18
3   Ashish  Jaiswal                NaN   19
4  Prateek  Rastogi  prateek@gmail.com   20
7      NaN      NaN  missing@gmail.com  NaN

In [13]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4  False  False  False  False
5   True   True   True   True
6   True   True   True   True
7   True   True  False   True

In [14]:
df.fillna(0)

     first     last              email age
0    Corey  Schafar    corey@gmail.com  33
1    Anand  Jaiswal    anand@gmail.com  18
2   Aditya  Jaiswal   aditya@gmail.com  18
3   Ashish  Jaiswal                  0  19
4  Prateek  Rastogi  prateek@gmail.com  20
5        0        0                  0   0
6        0        0                  0   0
7        0        0  missing@gmail.com   0

In [15]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [16]:
type(np.nan)  # nan is a float value

float

In [17]:
# casting data types

In [18]:
# df['age'] =df['age'].astype(int) # gives error as nan is float and we are converting it to int

In [19]:
df['age']=df['age'].astype(float)

In [20]:
df['age'].mean()

np.float64(21.6)

In [21]:
df.mean(numeric_only=True)

age    21.6
dtype: float64

In [22]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object