In [2]:
import pandas as pd

In [3]:
df =pd.read_csv('survey_results_public.csv',low_memory =False)
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['ConvertedCompYearly'].median()

np.float64(75320.0)

In [7]:
df.median(numeric_only=True)  # calculates median of all columns having numerical values

ResponseId              24596.0
WorkExp                    10.0
YearsCode                  14.0
TechEndorse_1               9.0
TechEndorse_2               4.0
TechEndorse_3               4.0
TechEndorse_4               6.0
TechEndorse_5               4.0
TechEndorse_6               5.0
TechEndorse_7               7.0
TechEndorse_8               4.0
TechEndorse_9               4.0
TechEndorse_13             10.0
TechOppose_1                9.0
TechOppose_2                4.0
TechOppose_3                6.0
TechOppose_5                5.0
TechOppose_7                4.0
TechOppose_9                3.0
TechOppose_11               4.0
TechOppose_13               5.0
TechOppose_16               6.0
TechOppose_15              10.0
JobSatPoints_1              6.0
JobSatPoints_2              4.0
JobSatPoints_3              7.0
JobSatPoints_4             10.0
JobSatPoints_5             10.0
JobSatPoints_6              8.0
JobSatPoints_7              5.0
JobSatPoints_8              7.0
JobSatPoints_9              6.0
JobSatPoints_10             7.0
JobSatPoints_11             5.0
JobSatPoints_13             9.0
JobSatPoints_14             9.0
JobSatPoints_15            15.0
JobSatPoints_16             8.0
ToolCountWork               6.0
ToolCountPersonal           5.0
CompTotal              105000.0
SO_Actions_1                5.0
SO_Actions_16               2.0
SO_Actions_3                6.0
SO_Actions_4                4.0
SO_Actions_5                5.0
SO_Actions_6                5.0
SO_Actions_9                6.0
SO_Actions_7                5.0
SO_Actions_10               8.0
SO_Actions_15              10.0
ConvertedCompYearly     75320.0
JobSat                      8.0
dtype: float64

In [9]:
df.dtypes  # tells the data types of each column

ResponseId               int64
MainBranch                 str
Age                        str
EdLevel                    str
Employment                 str
                        ...
AIAgentExtWrite            str
AIHuman                    str
AIOpen                     str
ConvertedCompYearly    float64
JobSat                 float64
Length: 172, dtype: object

In [13]:
df.median(numeric_only=True,axis=1)  # claculates median of each numeric value in each row

0            8.0
1            7.5
2            7.5
3            7.0
4            7.0
          ...
49186    49187.0
49187    24606.5
49188        7.5
49189    24596.0
49190    24598.5
Length: 49191, dtype: float64

In [15]:
df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,...,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,...,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,...,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [31]:
df['MainBranch'].value_counts()

MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64

In [34]:
df['MainBranch'].value_counts(normalize=True) # gives percentage of  answers

MainBranch
I am a developer by profession                                                                0.761664
I am not primarily a developer, but I write code sometimes as part of my work/studies         0.099490
I am learning to code                                                                         0.052550
I code primarily as a hobby                                                                   0.039113
I used to be a developer by profession, but no longer am                                      0.026936
I work with developers or my work supports developers but am not a developer by profession    0.020248
Name: proportion, dtype: float64

In [28]:
pd.set_option('display.max_columns',None)
schema_df = pd.read_csv('survey_results_schema.csv',low_memory=False)
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,Rank the following attributes of your current ...,RO,You like your manager,3.0
25,QID27,JobSatPoints_3,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,Rank the following attributes of your current ...,RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
28,QID27,JobSatPoints_6,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
31,QID27,JobSatPoints_9,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
32,QID27,JobSatPoints_10,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select...,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the high...,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your cur...,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</str...,MC,NaN,NaN
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Se...,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past y...,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have y...",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current ...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people ma...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professi...,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current ...,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transit...,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
74,QID22,CompTotal,What is your current total <b>annual</b> compe...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,Was the programming language you use not liste...,TE,NaN,NaN
78,QID52,LanguagesWantEntry,Was the programming language you want to use n...,TE,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,Was the database environment you use not liste...,TE,NaN,NaN
82,QID55,DatabaseWantEntry,Was the database environment you want to use n...,TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
93,QID60,DevEnvHaveEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
94,QID61,DevEnvWantEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
96,QID62,SOTagsHaveEntry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
97,QID63,SOTagsWant Entry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
102,QID42,CommPlatform,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
103,QID66,CommPlatformHaveEntr,Was the community platform you use not listed ...,TE,NaN,NaN
104,QID67,CommPlatformWantEntr,Was the community platform you want to use not...,TE,NaN,NaN
105,QID50,AIModelsChoice,Did you utilize or integrate specific Large La...,MC,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
107,QID68,AIModelsHaveEntry,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
108,QID69,AIModelsWantEntry,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
109,QID72,SOAccount,Do you have a Stack Overflow account?,MC,NaN,NaN
110,QID70,SOVisitFreq,How frequently would you say you visit Stack O...,MC,NaN,NaN
111,QID71,SODuration,How long have you used Stack Overflow?,MC,NaN,NaN
112,QID73,SOPartFreq,How frequently would you say you participate i...,MC,NaN,NaN
113,QID75,SO_Dev_Content,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
114,QID77,SOComm,Do you consider yourself a member of the Stack...,MC,NaN,NaN
115,QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
116,QID78,AISelect,Do you currently use AI tools in your developm...,MC,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
121,QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
126,QID106,AgentUsesGeneral,,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
128,QID88,AIAgentChallenges,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [24]:
schema_df.loc[137,'question']

'In the future, if AI can do most coding tasks, in which situations would you still want to ask another person for help? Select all that apply.'

In [25]:
schema_df.loc[137].value_counts()

137
QID100                                                                                                                                            1
AIHuman                                                                                                                                           1
In the future, if AI can do most coding tasks, in which situations would you still want to ask another person for help? Select all that apply.    1
MC                                                                                                                                                1
Name: count, dtype: int64

In [37]:
df['Country'].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
Canada                                                  1305
Ukraine                                                  964
Poland                                                   888
Netherlands                                              867
Italy                                                    835
Brazil                                                   825
Australia                                                804
Spain                                                    717
Sweden                                                   616
Switzerland                                              546
Czech Republic                                           520
Austria                                                  410
Romania                                                  323
Belgium                                                  321
Denmark                                                  316
Israel                                                   297
Turkey                                                   295
Mexico                                                   286
Portugal                                                 280
China                                                    255
New Zealand                                              255
Finland                                                  254
South Africa                                             253
Greece                                                   252
Bulgaria                                                 244
Pakistan                                                 239
Norway                                                   237
Hungary                                                  236
Argentina                                                222
Bangladesh                                               220
Ireland                                                  209
Colombia                                                 202
Russian Federation                                       200
Nigeria                                                  199
Japan                                                    188
Indonesia                                                181
Serbia                                                   158
Iran, Islamic Republic of...                             149
Kenya                                                    148
Slovakia                                                 147
Viet Nam                                                 145
Philippines                                              142
Egypt                                                    140
Chile                                                    131
Thailand                                                 119
Taiwan                                                   118
Croatia                                                  113
Lithuania                                                101
Sri Lanka                                                 95
United Arab Emirates                                      89
Singapore                                                 89
Nepal                                                     83
Malaysia                                                  82
Slovenia                                                  78
Hong Kong (S.A.R.)                                        72
Estonia                                                   70
Peru                                                      64
Latvia                                                    62
Morocco                                                   55
Uruguay                                                   52
Algeria                                                   49
Georgia                                                   48
South Korea                                               48
Venezuela, Bolivarian Republic of...                      47
Tunisia                                                   46
Ghana                                                     46
Cyprus                                                    39
Ethiopia                                                  38
Republic of Korea                                         38
Saudi Arabia                                              37
Guatemala                                                 33
Jordan                                                    32
Bosnia and Herzegovina                                    30
Kazakhstan                                                29
Nomadic                                                   29
Uganda                                                    28
Ecuador                                                   28
Costa Rica                                                27
Dominican Republic                                        26
Belarus                                                   26
Armenia                                                   25
Luxembourg                                                23
Albania                                                   22
Paraguay                                                  21
Republic of North Macedonia                               20
Lebanon                                                   20
Malta                                                     19
Bolivia                                                   18
Yemen                                                     18
Azerbaijan                                                18
Myanmar                                                   17
Uzbekistan                                                16
Montenegro                                                15
Rwanda                                                    15
Zimbabwe                                                  13
Iraq                                                      13
Zambia                                                    13
Cameroon                                                  13
Afghanistan                                               13
Iceland                                                   13
El Salvador                                               12
Madagascar                                                11
Honduras                                                  11
Cambodia                                                  11
Mauritius                                                 11
Syrian Arab Republic                                      11
Kyrgyzstan                                                10
Panama                                                    10
Isle of Man                                               10
Togo                                                       9
Maldives                                                   9
Moldova                                                    9
Republic of Moldova                                        8
Côte d'Ivoire                                              8
Cuba                                                       8
Trinidad and Tobago                                        7
Bahrain                                                    7
Angola                                                     7
Palestine                                                  7
Namibia                                                    7
Democratic Republic of the Congo                           7
United Republic of Tanzania                                7
Kuwait                                                     7
Nicaragua                                                  6
Kosovo                                                     6
Oman                                                       6
North Korea                                                6
Andorra                                                    6
Qatar                                                      5
Mozambique                                                 5
Fiji                                                       5
Swaziland                                                  5
Benin                                                      5
Senegal                                                    5
Congo, Republic of the...                                  5
Democratic People's Republic of Korea                      4
Guyana                                                     4
Jamaica                                                    4
Somalia                                                    4
Barbados                                                   4
Malawi                                                     4
Sudan                                                      3
Belize                                                     3
Bhutan                                                     3
Brunei Darussalam                                          3
Mongolia                                                   3
Papua New Guinea                                           3
Saint Lucia                                                2
Haiti                                                      2
Tajikistan                                                 2
Suriname                                                   2
Botswana                                                   2
Micronesia, Federated States of...                         2
Mali                                                       2
Lao People's Democratic Republic                           2
Turkmenistan                                               2
Libyan Arab Jamahiriya                                     2
Antigua and Barbuda                                        2
Sierra Leone                                               2
Burundi                                                    2
Mauritania                                                 1
Timor-Leste                                                1
Gabon                                                      1
Guinea-Bissau                                              1
Gambia                                                     1
Niger                                                      1
Lesotho                                                    1
San Marino                                                 1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, dtype: int64

In [49]:
country_df = df.groupby('Country') 
# groups dataframe for a countrywise

In [50]:
country_df

In [53]:
#country_df.groups.keys()
country_df.get_group('India').head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [56]:
# we can also use this , but writing it all the time is tidious
df[df['Country']=='India'].head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [61]:
country_df.get_group('India')['Employment'].value_counts()

Employment
Employed                                                1698
Student                                                  453
Independent contractor, freelancer, or self-employed     238
Not employed                                             126
I prefer not to say                                       25
Retired                                                    7
Name: count, dtype: int64

In [63]:
country_df['Employment'].value_counts().head(50)

Country              Employment
Afghanistan          Employed                                                  7
                     Student                                                   3
                     Independent contractor, freelancer, or self-employed      2
                     Not employed                                              1
Albania              Employed                                                 13
                     Independent contractor, freelancer, or self-employed      7
                     Student                                                   1
                     I prefer not to say                                       1
Algeria              Student                                                  17
                     Independent contractor, freelancer, or self-employed     16
                     Employed                                                 12
                     Not employed                                              3
                     I prefer not to say                                       1
Andorra              Employed                                                  3
                     Independent contractor, freelancer, or self-employed      2
                     Student                                                   1
Angola               Employed                                                  4
                     Student                                                   2
                     Independent contractor, freelancer, or self-employed      1
Antigua and Barbuda  Employed                                                  2
Argentina            Employed                                                125
                     Independent contractor, freelancer, or self-employed     64
                     Student                                                  16
                     Not employed                                             14
                     Retired                                                   2
                     I prefer not to say                                       1
Armenia              Employed                                                 22
                     Independent contractor, freelancer, or self-employed      3
Australia            Employed                                                562
                     Independent contractor, freelancer, or self-employed    125
                     Student                                                  57
                     Retired                                                  30
                     Not employed                                             28
                     I prefer not to say                                       2
Austria              Employed                                                310
                     Independent contractor, freelancer, or self-employed     53
                     Student                                                  31
                     Not employed                                              8
                     I prefer not to say                                       4
                     Retired                                                   4
Azerbaijan           Employed                                                 10
                     Independent contractor, freelancer, or self-employed      3
                     Not employed                                              2
                     Student                                                   2
                     I prefer not to say                                       1
Bahrain              Employed                                                  5
                     Student                                                   2
Bangladesh           Employed                                                130
                     Independent contractor, freelancer, or self-employed     39
                     Student                                                  37
Name: count, dtype: int64

In [68]:
country_df['Employment'].value_counts(normalize=True).loc['India']  # to find the employment percentage in india we use loc on this

Employment
Employed                                                0.666667
Student                                                 0.177856
Independent contractor, freelancer, or self-employed    0.093443
Not employed                                            0.049470
I prefer not to say                                     0.009815
Retired                                                 0.002748
Name: proportion, dtype: float64

In [66]:
country_df['ConvertedCompYearly'].median().head()

Country
Afghanistan      6121.0
Albania         26269.0
Algeria          6472.0
Andorra        200125.5
Angola           9578.0
Name: ConvertedCompYearly, dtype: float64

In [67]:
country_df['ConvertedCompYearly'].median().loc['China']

np.float64(34125.0)

In [70]:
country_df['ConvertedCompYearly'].agg(['median','mean']) # gives aggregate values of median and mean of salary in each country

                                                      median           mean
Country
Afghanistan                                           6121.0   12227.250000
Albania                                              26269.0   47973.583333
Algeria                                               6472.0   15935.400000
Andorra                                             200125.5  208763.750000
Angola                                                9578.0  149857.250000
Antigua and Barbuda                                      1.0       1.000000
Argentina                                            40000.0   46271.187500
Armenia                                               9076.0   25016.363636
Australia                                            97514.0  115941.413005
Austria                                              78310.0   79477.625000
Azerbaijan                                           29397.0   31202.333333
Bahrain                                              74240.5   74240.500000
Bangladesh                                            7895.5   15520.941667
Barbados                                             45450.5   45450.500000
Belarus                                              46614.5   58267.312500
Belgium                                              69609.0   84666.275229
Belize                                              102121.0  102121.000000
Benin                                                 1698.0    6816.333333
Bhutan                                               20361.0   20361.000000
Bolivia                                              18784.0   25214.307692
Bosnia and Herzegovina                               47000.0   51890.473684
Botswana                                              1277.0    1277.000000
Brazil                                               27306.0   51690.289515
Brunei Darussalam                                        NaN            NaN
Bulgaria                                             49817.5   54613.575949
Burundi                                               1697.0    1697.000000
Cambodia                                              1500.0    4694.000000
Cameroon                                              1265.5    4547.000000
Canada                                               87550.0  100143.382514
Cape Verde                                               NaN            NaN
Chile                                                33930.0   39241.252632
China                                                34125.0   47847.632479
Colombia                                             20500.0   31370.534351
Congo, Republic of the...                            42811.5   42811.500000
Costa Rica                                           59500.0   71422.111111
Croatia                                              46406.0   55424.829268
Cuba                                                 14041.5   71668.875000
Cyprus                                               92812.0   91799.041667
Czech Republic                                       60660.0   67003.573407
Côte d'Ivoire                                        33966.0   75877.200000
Democratic People's Republic of Korea                    NaN            NaN
Democratic Republic of the Congo                     30000.0   33000.000000
Denmark                                              98678.0  106030.465217
Djibouti                                              5833.0    5833.000000
Dominican Republic                                   27681.5   44179.600000
Ecuador                                              30000.0   40952.260870
Egypt                                                 6595.0   14453.921875
El Salvador                                          27000.0   41800.000000
Estonia                                              69609.0   76545.326923
Ethiopia                                               762.0   33087.166667
Fiji                                                     NaN            NaN
Finland                                              74249.0   85162.361257
France                                               63228.0   73778.737098
Gabon                                                    NaN            NaN
Gambia                                                   NaN            NaN
Georgia                                              53653.5   56644.250000
Germany                                              81210.0   86443.718356
Ghana                                                 2610.0    9833.318182
Greece                                               44260.0   53055.137931
Guatemala                                            29668.0   37647.896552
Guinea                                                2773.0    2773.000000
Guinea-Bissau                                            NaN            NaN
Guyana                                               35871.0   31566.333333
Haiti                                                 9149.0    9149.000000
Honduras                                             11982.0   22198.833333
Hong Kong (S.A.R.)                                   76433.0  111564.300000
Hungary                                              46266.0   55376.591716
Iceland                                             117637.0   88158.714286
India                                                17029.0   44291.789234
Indonesia                                             5638.0   17902.716049
Iran, Islamic Republic of...                         18516.0  277297.200000
Iraq                                                 18000.0   15420.666667
Ireland                                             116015.0  121326.818182
Isle of Man                                          83632.0   82521.444444
Israel                                              141188.0  131723.762712
Italy                                                47566.0   55911.454389
Jamaica                                              96796.5   96796.500000
Japan                                                58725.0   73440.617188
Jordan                                               30000.0   34879.826087
Kazakhstan                                           28381.5   33210.611111
Kenya                                                 6502.0   31946.506849
Kosovo                                               45245.5   50176.250000
Kuwait                                               26838.0   44543.600000
Kyrgyzstan                                           12605.0   41211.000000
Lao People's Democratic Republic                         7.0       7.000000
Latvia                                               51845.5   84648.050000
Lebanon                                              47000.0   77244.444444
Lesotho                                               2822.0    2822.000000
Libyan Arab Jamahiriya                                5541.0    5541.000000
Lithuania                                            66708.0   71457.739130
Luxembourg                                           98612.0  101348.235294
Madagascar                                            5288.0   16751.125000
Malawi                                               11252.5   11252.500000
Malaysia                                             18261.0   24403.434783
Maldives                                             24600.5   25039.500000
Mali                                                 11941.5   11941.500000
Malta                                                70189.0   69516.187500
Mauritania                                          121570.0  121570.000000
Mauritius                                            15976.0   16405.800000
Mexico                                               28951.0   37245.638743
Micronesia, Federated States of...                       1.0       1.000000
Moldova                                              29177.5   37324.500000
Mongolia                                             29757.0   31626.666667
Montenegro                                           42873.0   59133.916667
Morocco                                              21987.0   24531.695652
Mozambique                                            9381.0   36629.200000
Myanmar                                               5716.0    8404.200000
Namibia                                               3923.0    8024.333333
Nepal                                                 4060.0   25012.536585
Netherlands                                          81210.0  115292.822294
New Zealand                                          81318.0   81957.436464
Nicaragua                                            47000.0   67822.500000
Niger                                                    NaN            NaN
Nigeria                                               1291.0   63181.843137
Nomadic                                             135157.5  135473.833333
North Korea                                         233924.5  233924.500000
Norway                                               88945.0   99256.809783
Oman                                                390135.0  261217.000000
Pakistan                                              6321.0   12997.733333
Palau                                                    NaN            NaN
Palestine                                               78.0      78.000000
Panama                                               26400.0   55300.000000
Papua New Guinea                                      7574.0    7574.000000
Paraguay                                             21178.0   42256.000000
Peru                                                 16998.0   31296.575000
Philippines                                          12291.0   23956.063291
Poland                                               60038.0   97821.346350
Portugal                                             60908.0   74386.754630
Qatar                                                46111.0   46111.000000
Republic of Korea                                    44096.0   82366.555556
Republic of Moldova                                  46924.0   51249.400000
Republic of North Macedonia                          29472.0   31328.300000
Romania                                              57437.0   64200.027907
Russian Federation                                   38278.0   42168.700787
Rwanda                                               15591.5   16245.700000
Saint Lucia                                          30810.5   30810.500000
San Marino                                               NaN            NaN
Saudi Arabia                                         32789.0   49335.388889
Senegal                                              11786.5   11786.500000
Serbia                                               48000.0   57883.798165
Sierra Leone                                             NaN            NaN
Singapore                                            92563.0  131430.187500
Slovakia                                             55687.0   58923.165049
Slovenia                                             56847.0   73555.661290
Somalia                                               5300.0    6766.666667
South Africa                                         43412.0   78843.243243
South Korea                                          33072.0   44968.304348
Spain                                                62648.0   70795.607143
Sri Lanka                                            10391.0   21905.372881
Sudan                                                 4864.5    4864.500000
Suriname                                             18686.5   18686.500000
Swaziland                                             4848.5    8145.250000
Sweden                                               70440.0   73943.915074
Switzerland                                         142592.0  151290.444976
Syrian Arab Republic                                  9845.5   13265.166667
Taiwan                                               33886.0   41913.571429
Tajikistan                                               NaN            NaN
Thailand                                             32123.0   47619.614035
Timor-Leste                                              NaN            NaN
Togo                                                   711.0    3688.333333
Trinidad and Tobago                                  29595.0   37923.250000
Tunisia                                               6517.0   13840.520000
Turkey                                               29000.0   38163.090426
Turkmenistan                                         35000.0   35000.000000
Uganda                                                4588.0   14159.833333
Ukraine                                              25021.0  105101.259520
United Arab Emirates                                 54460.0  105481.808511
United Kingdom of Great Britain and Northern Ir...   94618.0  112948.493943
United Republic of Tanzania                           5014.0   12041.200000
United States of America                            150000.0  179804.501621
Uruguay                                              49338.0   78567.414634
Uzbekistan                                            9675.0   12593.555556
Venezuela, Bolivarian Republic of...                  9000.0   17008.400000
Viet Nam                                              7642.0  189894.192982
Yemen                                                 5545.5   17582.500000
Zambia                                                1966.5    6594.875000
Zimbabwe                                             17500.0   25662.500000

In [77]:

df[df['Country']=='India']['LanguageHaveWorkedWith'].str.contains('C++').sum()  # counts how many prople in india have worked with c++ , takes 1 for true and 0 for false

np.int64(1532)

In [78]:
country_df['LanguageHaveWorkedWith'].str.contains('C++').sum()  # this does not works because str works on string not on series and here country_df['LanguageHaveWorkedWith'] gives us series , so we use aply method

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [91]:
percentage =country_df['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('C++').value_counts(normalize=True)*100).head(50)
percentage

Country
Afghanistan             False     53.846154
                        True      46.153846
Albania                 True      72.727273
                        False     27.272727
Algeria                 True      65.306122
                        False     34.693878
Andorra                 True      83.333333
                        False     16.666667
Angola                  False     57.142857
                        True      42.857143
Antigua and Barbuda     False     50.000000
                        True      50.000000
Argentina               True      72.072072
                        False     27.927928
Armenia                 False     52.000000
                        True      48.000000
Australia               True      77.363184
                        False     22.636816
Austria                 True      78.780488
                        False     21.219512
Azerbaijan              True      72.222222
                        False     27.777778
Bahrain                 True      71.428571
                        False     28.571429
Bangladesh              True      62.272727
                        False     37.727273
Barbados                False     50.000000
                        True      50.000000
Belarus                 False     50.000000
                        True      50.000000
Belgium                 True      77.570093
                        False     22.429907
Belize                  True      66.666667
                        False     33.333333
Benin                   True      80.000000
                        False     20.000000
Bhutan                  False    100.000000
Bolivia                 True      72.222222
                        False     27.777778
Bosnia and Herzegovina  True      73.333333
                        False     26.666667
Botswana                True     100.000000
Brazil                  True      68.000000
                        False     32.000000
Brunei Darussalam       True      66.666667
                        False     33.333333
Bulgaria                True      69.262295
                        False     30.737705
Burundi                 True     100.000000
Cambodia                True      81.818182
Name: LanguageHaveWorkedWith, dtype: float64

In [92]:
# calculating how many people in each country know python
Total_respondents = df['Country'].value_counts()
Total_respondents

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
Canada                                                  1305
Ukraine                                                  964
Poland                                                   888
Netherlands                                              867
Italy                                                    835
Brazil                                                   825
Australia                                                804
Spain                                                    717
Sweden                                                   616
Switzerland                                              546
Czech Republic                                           520
Austria                                                  410
Romania                                                  323
Belgium                                                  321
Denmark                                                  316
Israel                                                   297
Turkey                                                   295
Mexico                                                   286
Portugal                                                 280
China                                                    255
New Zealand                                              255
Finland                                                  254
South Africa                                             253
Greece                                                   252
Bulgaria                                                 244
Pakistan                                                 239
Norway                                                   237
Hungary                                                  236
Argentina                                                222
Bangladesh                                               220
Ireland                                                  209
Colombia                                                 202
Russian Federation                                       200
Nigeria                                                  199
Japan                                                    188
Indonesia                                                181
Serbia                                                   158
Iran, Islamic Republic of...                             149
Kenya                                                    148
Slovakia                                                 147
Viet Nam                                                 145
Philippines                                              142
Egypt                                                    140
Chile                                                    131
Thailand                                                 119
Taiwan                                                   118
Croatia                                                  113
Lithuania                                                101
Sri Lanka                                                 95
United Arab Emirates                                      89
Singapore                                                 89
Nepal                                                     83
Malaysia                                                  82
Slovenia                                                  78
Hong Kong (S.A.R.)                                        72
Estonia                                                   70
Peru                                                      64
Latvia                                                    62
Morocco                                                   55
Uruguay                                                   52
Algeria                                                   49
Georgia                                                   48
South Korea                                               48
Venezuela, Bolivarian Republic of...                      47
Tunisia                                                   46
Ghana                                                     46
Cyprus                                                    39
Ethiopia                                                  38
Republic of Korea                                         38
Saudi Arabia                                              37
Guatemala                                                 33
Jordan                                                    32
Bosnia and Herzegovina                                    30
Kazakhstan                                                29
Nomadic                                                   29
Uganda                                                    28
Ecuador                                                   28
Costa Rica                                                27
Dominican Republic                                        26
Belarus                                                   26
Armenia                                                   25
Luxembourg                                                23
Albania                                                   22
Paraguay                                                  21
Republic of North Macedonia                               20
Lebanon                                                   20
Malta                                                     19
Bolivia                                                   18
Yemen                                                     18
Azerbaijan                                                18
Myanmar                                                   17
Uzbekistan                                                16
Montenegro                                                15
Rwanda                                                    15
Zimbabwe                                                  13
Iraq                                                      13
Zambia                                                    13
Cameroon                                                  13
Afghanistan                                               13
Iceland                                                   13
El Salvador                                               12
Madagascar                                                11
Honduras                                                  11
Cambodia                                                  11
Mauritius                                                 11
Syrian Arab Republic                                      11
Kyrgyzstan                                                10
Panama                                                    10
Isle of Man                                               10
Togo                                                       9
Maldives                                                   9
Moldova                                                    9
Republic of Moldova                                        8
Côte d'Ivoire                                              8
Cuba                                                       8
Trinidad and Tobago                                        7
Bahrain                                                    7
Angola                                                     7
Palestine                                                  7
Namibia                                                    7
Democratic Republic of the Congo                           7
United Republic of Tanzania                                7
Kuwait                                                     7
Nicaragua                                                  6
Kosovo                                                     6
Oman                                                       6
North Korea                                                6
Andorra                                                    6
Qatar                                                      5
Mozambique                                                 5
Fiji                                                       5
Swaziland                                                  5
Benin                                                      5
Senegal                                                    5
Congo, Republic of the...                                  5
Democratic People's Republic of Korea                      4
Guyana                                                     4
Jamaica                                                    4
Somalia                                                    4
Barbados                                                   4
Malawi                                                     4
Sudan                                                      3
Belize                                                     3
Bhutan                                                     3
Brunei Darussalam                                          3
Mongolia                                                   3
Papua New Guinea                                           3
Saint Lucia                                                2
Haiti                                                      2
Tajikistan                                                 2
Suriname                                                   2
Botswana                                                   2
Micronesia, Federated States of...                         2
Mali                                                       2
Lao People's Democratic Republic                           2
Turkmenistan                                               2
Libyan Arab Jamahiriya                                     2
Antigua and Barbuda                                        2
Sierra Leone                                               2
Burundi                                                    2
Mauritania                                                 1
Timor-Leste                                                1
Gabon                                                      1
Guinea-Bissau                                              1
Gambia                                                     1
Niger                                                      1
Lesotho                                                    1
San Marino                                                 1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, dtype: int64

In [111]:
pwkPython= country_df['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('Python').sum())
pwkPython.head()

Country
Afghanistan     4
Albania        10
Algeria        23
Andorra         2
Angola          1
Name: LanguageHaveWorkedWith, dtype: int64

In [112]:
# creating a new df 
calculate_pcwkpython = pd.concat([pwkPython,Total_respondents],axis='columns')
calculate_pcwkpython

,LanguageHaveWorkedWith,count
Country,,
Afghanistan,4,13
Albania,10,22
Algeria,23,49
Andorra,2,6
Angola,1,7
Antigua and Barbuda,1,2
Argentina,108,222
Armenia,7,25
Australia,418,804
Austria,222,410
Azerbaijan,8,18
Bahrain,4,7
Bangladesh,88,220
Barbados,2,4
Belarus,7,26
Belgium,166,321
Belize,1,3
Benin,3,5
Bhutan,2,3
Bolivia,8,18
Bosnia and Herzegovina,10,30
Botswana,1,2
Brazil,407,825
Brunei Darussalam,2,3
Bulgaria,107,244
Burundi,1,2
Cambodia,4,11
Cameroon,6,13
Canada,687,1305
Cape Verde,1,1
Chile,82,131
China,152,255
Colombia,113,202
"Congo, Republic of the...",1,5
Costa Rica,16,27
Croatia,44,113
Cuba,6,8
Cyprus,15,39
Czech Republic,259,520
Côte d'Ivoire,4,8
Democratic People's Republic of Korea,3,4
Democratic Republic of the Congo,2,7
Denmark,151,316
Djibouti,0,1
Dominican Republic,11,26
Ecuador,15,28
Egypt,45,140
El Salvador,3,12
Estonia,30,70
Ethiopia,11,38
Fiji,3,5
Finland,155,254
France,820,1409
Gabon,0,1
Gambia,1,1
Georgia,22,48
Germany,1685,3025
Ghana,25,46
Greece,115,252
Guatemala,17,33
Guinea,1,1
Guinea-Bissau,1,1
Guyana,2,4
Haiti,2,2
Honduras,4,11
Hong Kong (S.A.R.),37,72
Hungary,120,236
Iceland,7,13
India,1162,2547
Indonesia,74,181
"Iran, Islamic Republic of...",56,149
Iraq,5,13
Ireland,104,209
Isle of Man,5,10
Israel,173,297
Italy,436,835
Jamaica,2,4
Japan,101,188
Jordan,11,32
Kazakhstan,17,29
Kenya,79,148
Kosovo,4,6
Kuwait,3,7
Kyrgyzstan,4,10
Lao People's Democratic Republic,1,2
Latvia,32,62
Lebanon,12,20
Lesotho,1,1
Libyan Arab Jamahiriya,0,2
Lithuania,49,101
Luxembourg,10,23
Madagascar,5,11
Malawi,2,4
Malaysia,41,82
Maldives,4,9
Mali,2,2
Malta,13,19
Mauritania,0,1
Mauritius,7,11
Mexico,140,286
"Micronesia, Federated States of...",0,2
Moldova,4,9
Mongolia,3,3
Montenegro,6,15
Morocco,31,55
Mozambique,2,5
Myanmar,7,17
Namibia,3,7
Nepal,39,83
Netherlands,458,867
New Zealand,136,255
Nicaragua,2,6
Niger,1,1
Nigeria,80,199
Nomadic,17,29
North Korea,3,6
Norway,110,237
Oman,2,6
Pakistan,96,239
Palau,1,1
Palestine,3,7
Panama,7,10
Papua New Guinea,1,3
Paraguay,8,21
Peru,26,64
Philippines,70,142
Poland,459,888
Portugal,155,280
Qatar,1,5
Republic of Korea,21,38
Republic of Moldova,1,8
Republic of North Macedonia,8,20
Romania,135,323
Russian Federation,110,200
Rwanda,9,15
Saint Lucia,2,2
San Marino,0,1
Saudi Arabia,19,37
Senegal,1,5
Serbia,74,158
Sierra Leone,0,2
Singapore,51,89
Slovakia,77,147
Slovenia,41,78
Somalia,1,4
South Africa,124,253
South Korea,23,48
Spain,398,717
Sri Lanka,51,95
Sudan,0,3
Suriname,2,2
Swaziland,2,5
Sweden,291,616
Switzerland,324,546
Syrian Arab Republic,5,11
Taiwan,63,118
Tajikistan,1,2
Thailand,59,119
Timor-Leste,0,1
Togo,2,9
Trinidad and Tobago,2,7
Tunisia,21,46
Turkey,130,295
Turkmenistan,0,2
Uganda,13,28
Ukraine,384,964
United Arab Emirates,39,89
United Kingdom of Great Britain and Northern Ireland,1027,2042
United Republic of Tanzania,2,7
United States of America,4221,7233
Uruguay,26,52
Uzbekistan,8,16
"Venezuela, Bolivarian Republic of...",23,47
Viet Nam,78,145
Yemen,6,18
Zambia,7,13
Zimbabwe,7,13

In [113]:
calculate_pcwkpython.rename(columns = {'LanguageHaveWorkedWith':'Know Python' , 'count' : 'total respondents'},inplace=True)

In [114]:
calculate_pcwkpython['percantage_know_python'] = calculate_pcwkpython['Know Python']/calculate_pcwkpython['total respondents']*100
calculate_pcwkpython

,Know Python,total respondents,percantage_know_python
Country,,,
Afghanistan,4,13,30.769231
Albania,10,22,45.454545
Algeria,23,49,46.938776
Andorra,2,6,33.333333
Angola,1,7,14.285714
Antigua and Barbuda,1,2,50.000000
Argentina,108,222,48.648649
Armenia,7,25,28.000000
Australia,418,804,51.990050
Austria,222,410,54.146341
Azerbaijan,8,18,44.444444
Bahrain,4,7,57.142857
Bangladesh,88,220,40.000000
Barbados,2,4,50.000000
Belarus,7,26,26.923077
Belgium,166,321,51.713396
Belize,1,3,33.333333
Benin,3,5,60.000000
Bhutan,2,3,66.666667
Bolivia,8,18,44.444444
Bosnia and Herzegovina,10,30,33.333333
Botswana,1,2,50.000000
Brazil,407,825,49.333333
Brunei Darussalam,2,3,66.666667
Bulgaria,107,244,43.852459
Burundi,1,2,50.000000
Cambodia,4,11,36.363636
Cameroon,6,13,46.153846
Canada,687,1305,52.643678
Cape Verde,1,1,100.000000
Chile,82,131,62.595420
China,152,255,59.607843
Colombia,113,202,55.940594
"Congo, Republic of the...",1,5,20.000000
Costa Rica,16,27,59.259259
Croatia,44,113,38.938053
Cuba,6,8,75.000000
Cyprus,15,39,38.461538
Czech Republic,259,520,49.807692
Côte d'Ivoire,4,8,50.000000
Democratic People's Republic of Korea,3,4,75.000000
Democratic Republic of the Congo,2,7,28.571429
Denmark,151,316,47.784810
Djibouti,0,1,0.000000
Dominican Republic,11,26,42.307692
Ecuador,15,28,53.571429
Egypt,45,140,32.142857
El Salvador,3,12,25.000000
Estonia,30,70,42.857143
Ethiopia,11,38,28.947368
Fiji,3,5,60.000000
Finland,155,254,61.023622
France,820,1409,58.197303
Gabon,0,1,0.000000
Gambia,1,1,100.000000
Georgia,22,48,45.833333
Germany,1685,3025,55.702479
Ghana,25,46,54.347826
Greece,115,252,45.634921
Guatemala,17,33,51.515152
Guinea,1,1,100.000000
Guinea-Bissau,1,1,100.000000
Guyana,2,4,50.000000
Haiti,2,2,100.000000
Honduras,4,11,36.363636
Hong Kong (S.A.R.),37,72,51.388889
Hungary,120,236,50.847458
Iceland,7,13,53.846154
India,1162,2547,45.622301
Indonesia,74,181,40.883978
"Iran, Islamic Republic of...",56,149,37.583893
Iraq,5,13,38.461538
Ireland,104,209,49.760766
Isle of Man,5,10,50.000000
Israel,173,297,58.249158
Italy,436,835,52.215569
Jamaica,2,4,50.000000
Japan,101,188,53.723404
Jordan,11,32,34.375000
Kazakhstan,17,29,58.620690
Kenya,79,148,53.378378
Kosovo,4,6,66.666667
Kuwait,3,7,42.857143
Kyrgyzstan,4,10,40.000000
Lao People's Democratic Republic,1,2,50.000000
Latvia,32,62,51.612903
Lebanon,12,20,60.000000
Lesotho,1,1,100.000000
Libyan Arab Jamahiriya,0,2,0.000000
Lithuania,49,101,48.514851
Luxembourg,10,23,43.478261
Madagascar,5,11,45.454545
Malawi,2,4,50.000000
Malaysia,41,82,50.000000
Maldives,4,9,44.444444
Mali,2,2,100.000000
Malta,13,19,68.421053
Mauritania,0,1,0.000000
Mauritius,7,11,63.636364
Mexico,140,286,48.951049
"Micronesia, Federated States of...",0,2,0.000000
Moldova,4,9,44.444444
Mongolia,3,3,100.000000
Montenegro,6,15,40.000000
Morocco,31,55,56.363636
Mozambique,2,5,40.000000
Myanmar,7,17,41.176471
Namibia,3,7,42.857143
Nepal,39,83,46.987952
Netherlands,458,867,52.825836
New Zealand,136,255,53.333333
Nicaragua,2,6,33.333333
Niger,1,1,100.000000
Nigeria,80,199,40.201005
Nomadic,17,29,58.620690
North Korea,3,6,50.000000
Norway,110,237,46.413502
Oman,2,6,33.333333
Pakistan,96,239,40.167364
Palau,1,1,100.000000
Palestine,3,7,42.857143
Panama,7,10,70.000000
Papua New Guinea,1,3,33.333333
Paraguay,8,21,38.095238
Peru,26,64,40.625000
Philippines,70,142,49.295775
Poland,459,888,51.689189
Portugal,155,280,55.357143
Qatar,1,5,20.000000
Republic of Korea,21,38,55.263158
Republic of Moldova,1,8,12.500000
Republic of North Macedonia,8,20,40.000000
Romania,135,323,41.795666
Russian Federation,110,200,55.000000
Rwanda,9,15,60.000000
Saint Lucia,2,2,100.000000
San Marino,0,1,0.000000
Saudi Arabia,19,37,51.351351
Senegal,1,5,20.000000
Serbia,74,158,46.835443
Sierra Leone,0,2,0.000000
Singapore,51,89,57.303371
Slovakia,77,147,52.380952
Slovenia,41,78,52.564103
Somalia,1,4,25.000000
South Africa,124,253,49.011858
South Korea,23,48,47.916667
Spain,398,717,55.509066
Sri Lanka,51,95,53.684211
Sudan,0,3,0.000000
Suriname,2,2,100.000000
Swaziland,2,5,40.000000
Sweden,291,616,47.240260
Switzerland,324,546,59.340659
Syrian Arab Republic,5,11,45.454545
Taiwan,63,118,53.389831
Tajikistan,1,2,50.000000
Thailand,59,119,49.579832
Timor-Leste,0,1,0.000000
Togo,2,9,22.222222
Trinidad and Tobago,2,7,28.571429
Tunisia,21,46,45.652174
Turkey,130,295,44.067797
Turkmenistan,0,2,0.000000
Uganda,13,28,46.428571
Ukraine,384,964,39.834025
United Arab Emirates,39,89,43.820225
United Kingdom of Great Britain and Northern Ireland,1027,2042,50.293830
United Republic of Tanzania,2,7,28.571429
United States of America,4221,7233,58.357528
Uruguay,26,52,50.000000
Uzbekistan,8,16,50.000000
"Venezuela, Bolivarian Republic of...",23,47,48.936170
Viet Nam,78,145,53.793103
Yemen,6,18,33.333333
Zambia,7,13,53.846154
Zimbabwe,7,13,53.846154

In [115]:
calculate_pcwkpython.sort_values('percantage_know_python',ascending =False)

,Know Python,total respondents,percantage_know_python
Country,,,
Cape Verde,1,1,100.000000
Lesotho,1,1,100.000000
Mali,2,2,100.000000
Niger,1,1,100.000000
Mongolia,3,3,100.000000
Guinea,1,1,100.000000
Palau,1,1,100.000000
Suriname,2,2,100.000000
Saint Lucia,2,2,100.000000
Haiti,2,2,100.000000
Guinea-Bissau,1,1,100.000000
Gambia,1,1,100.000000
Cuba,6,8,75.000000
Democratic People's Republic of Korea,3,4,75.000000
Panama,7,10,70.000000
Malta,13,19,68.421053
Bhutan,2,3,66.666667
Kosovo,4,6,66.666667
Brunei Darussalam,2,3,66.666667
Mauritius,7,11,63.636364
Chile,82,131,62.595420
Finland,155,254,61.023622
Benin,3,5,60.000000
Fiji,3,5,60.000000
Lebanon,12,20,60.000000
Rwanda,9,15,60.000000
China,152,255,59.607843
Switzerland,324,546,59.340659
Costa Rica,16,27,59.259259
Nomadic,17,29,58.620690
Kazakhstan,17,29,58.620690
United States of America,4221,7233,58.357528
Israel,173,297,58.249158
France,820,1409,58.197303
Singapore,51,89,57.303371
Bahrain,4,7,57.142857
Morocco,31,55,56.363636
Colombia,113,202,55.940594
Germany,1685,3025,55.702479
Spain,398,717,55.509066
Portugal,155,280,55.357143
Republic of Korea,21,38,55.263158
Russian Federation,110,200,55.000000
Ghana,25,46,54.347826
Austria,222,410,54.146341
Zambia,7,13,53.846154
Zimbabwe,7,13,53.846154
Iceland,7,13,53.846154
Viet Nam,78,145,53.793103
Japan,101,188,53.723404
Sri Lanka,51,95,53.684211
Ecuador,15,28,53.571429
Taiwan,63,118,53.389831
Kenya,79,148,53.378378
New Zealand,136,255,53.333333
Netherlands,458,867,52.825836
Canada,687,1305,52.643678
Slovenia,41,78,52.564103
Slovakia,77,147,52.380952
Italy,436,835,52.215569
Australia,418,804,51.990050
Belgium,166,321,51.713396
Poland,459,888,51.689189
Latvia,32,62,51.612903
Guatemala,17,33,51.515152
Hong Kong (S.A.R.),37,72,51.388889
Saudi Arabia,19,37,51.351351
Hungary,120,236,50.847458
United Kingdom of Great Britain and Northern Ireland,1027,2042,50.293830
Barbados,2,4,50.000000
Malaysia,41,82,50.000000
North Korea,3,6,50.000000
Uzbekistan,8,16,50.000000
Uruguay,26,52,50.000000
Malawi,2,4,50.000000
Lao People's Democratic Republic,1,2,50.000000
Guyana,2,4,50.000000
Antigua and Barbuda,1,2,50.000000
Côte d'Ivoire,4,8,50.000000
Burundi,1,2,50.000000
Botswana,1,2,50.000000
Jamaica,2,4,50.000000
Tajikistan,1,2,50.000000
Isle of Man,5,10,50.000000
Czech Republic,259,520,49.807692
Ireland,104,209,49.760766
Thailand,59,119,49.579832
Brazil,407,825,49.333333
Philippines,70,142,49.295775
South Africa,124,253,49.011858
Mexico,140,286,48.951049
"Venezuela, Bolivarian Republic of...",23,47,48.936170
Argentina,108,222,48.648649
Lithuania,49,101,48.514851
South Korea,23,48,47.916667
Denmark,151,316,47.784810
Sweden,291,616,47.240260
Nepal,39,83,46.987952
Algeria,23,49,46.938776
Serbia,74,158,46.835443
Uganda,13,28,46.428571
Norway,110,237,46.413502
Cameroon,6,13,46.153846
Georgia,22,48,45.833333
Tunisia,21,46,45.652174
Greece,115,252,45.634921
India,1162,2547,45.622301
Madagascar,5,11,45.454545
Syrian Arab Republic,5,11,45.454545
Albania,10,22,45.454545
Bolivia,8,18,44.444444
Moldova,4,9,44.444444
Azerbaijan,8,18,44.444444
Maldives,4,9,44.444444
Turkey,130,295,44.067797
Bulgaria,107,244,43.852459
United Arab Emirates,39,89,43.820225
Luxembourg,10,23,43.478261
Estonia,30,70,42.857143
Palestine,3,7,42.857143
Kuwait,3,7,42.857143
Namibia,3,7,42.857143
Dominican Republic,11,26,42.307692
Romania,135,323,41.795666
Myanmar,7,17,41.176471
Indonesia,74,181,40.883978
Peru,26,64,40.625000
Nigeria,80,199,40.201005
Pakistan,96,239,40.167364
Kyrgyzstan,4,10,40.000000
Republic of North Macedonia,8,20,40.000000
Montenegro,6,15,40.000000
Mozambique,2,5,40.000000
Swaziland,2,5,40.000000
Bangladesh,88,220,40.000000
Ukraine,384,964,39.834025
Croatia,44,113,38.938053
Iraq,5,13,38.461538
Cyprus,15,39,38.461538
Paraguay,8,21,38.095238
"Iran, Islamic Republic of...",56,149,37.583893
Cambodia,4,11,36.363636
Honduras,4,11,36.363636
Jordan,11,32,34.375000
Andorra,2,6,33.333333
Papua New Guinea,1,3,33.333333
Bosnia and Herzegovina,10,30,33.333333
Belize,1,3,33.333333
Yemen,6,18,33.333333
Oman,2,6,33.333333
Nicaragua,2,6,33.333333
Egypt,45,140,32.142857
Afghanistan,4,13,30.769231
Ethiopia,11,38,28.947368
United Republic of Tanzania,2,7,28.571429
Democratic Republic of the Congo,2,7,28.571429
Trinidad and Tobago,2,7,28.571429
Armenia,7,25,28.000000
Belarus,7,26,26.923077
Somalia,1,4,25.000000
El Salvador,3,12,25.000000
Togo,2,9,22.222222
Qatar,1,5,20.000000
"Congo, Republic of the...",1,5,20.000000
Senegal,1,5,20.000000
Angola,1,7,14.285714
Republic of Moldova,1,8,12.500000
Djibouti,0,1,0.000000
Gabon,0,1,0.000000
"Micronesia, Federated States of...",0,2,0.000000
Mauritania,0,1,0.000000
Libyan Arab Jamahiriya,0,2,0.000000
San Marino,0,1,0.000000
Sierra Leone,0,2,0.000000
Sudan,0,3,0.000000
Timor-Leste,0,1,0.000000
Turkmenistan,0,2,0.000000

In [116]:
calculate_pcwkpython.loc['Japan']

Know Python               101.000000
total respondents         188.000000
percantage_know_python     53.723404
Name: Japan, dtype: float64